# Generated by Django 3.0.1 on 2019-12-23 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulanyjy',
            name='ady',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='bölümi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dokument_Dolanysygy.Bolumler'),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='döreden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='edarasy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dokument_Dolanysygy.Edaralar'),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='mac_adresi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ulanyjy',
            name='welaýaty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dokument_Dolanysygy.Welayatlar'),
        ),
    ]
