# Generated by Django 3.0.1 on 2019-12-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0003_auto_20191223_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulanyjy',
            name='welaýaty',
        ),
    ]
