# Generated by Django 3.0.1 on 2019-12-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0004_remove_ulanyjy_welaýaty'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mazmuny',
            field=models.TextField(default='sad'),
            preserve_default=False,
        ),
    ]
