# Generated by Django 3.0.1 on 2019-12-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0005_file_mazmuny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='welaýaty',
        ),
    ]
