# Generated by Django 3.0.1 on 2019-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0007_auto_20191223_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mazmuny',
            field=models.TextField(blank=True, null=True),
        ),
    ]
