# Generated by Django 3.0.1 on 2019-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0008_auto_20191225_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mazmuny_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mazmuny_tr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
