# Generated by Django 3.0.1 on 2019-12-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dokument_Dolanysygy', '0011_auto_20191226_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulanyjy',
            name='edarasy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dokument_Dolanysygy.Edaralar'),
        ),
    ]
